### PR TITLE
Reduce Docker image size from 619 MB to 154 MB

### PR DESCRIPTION
**Pull request by davidcorbin**

### CODE REVIEW

**Comment by hyness** [comment]
Nice work.  I think it would be nice to allow users to decide if they want to sacrifice size for a more updated jvm (adoptjdk, jdk11, jdk14, etc).  This will bring the image size back down until that happens.  Thanks for the contribution.

**Comment by davidcorbin** [comment]
I agree, that would be nice. There could be dockerfiles for each version and add CI builds for each of the multiple versions. Definitely should keep the multistage buildS so that layers with the source and compiled Java classes aren’t unnecessarily included in the final Docker image.

**Comment by hyness** [comment]
@davidcorbin, your contribution has inspired me to implement the multiple jdk options I’ve planned to do for a long time. If you would like your name to be added to the Dockerfiles as a maintainer, please create a pull request.  Thanks again for your contribution

**Comment by davidcorbin** [comment]
Thanks for the kind words! I noticed that some of the tags that are in the README are slightly different than they are on Docker hub. For example, `2.2.3-RELEASE-jdk8` in the README is actually `2.2.3.RELEASE-jdk8` on Docker hub causing docker pulls to fail for anyone just checking the README.

**Comment by hyness** [comment]
Good catch.  Fixed.

**Pull request merged**
